# Site title and subtitle. This is used in _includes/header.html
title: 'Automation Hub'
subtitle: 'Documentation'

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/automation-hub'

gettting_started_img: '/automation-hub/img/getting-started'

terminology_img: '/automation-hub/img/terminology'

first_program_img: '/automation-hub/img/first-program'

collections:
  pages:
    output: true

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: rouge

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the kramdown Markdown renderer
markdown: kramdown
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]
